spring:
  datasource:
    password: postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/room
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 8086
  error:
    include-message: always
sql:
  query:
    sql-change-account-non-locked: update profile set account_non_locked = ? where id = ?